#!/usr/bin/env python3
"""Validate CycloneDX and SPDX SBOMs generated by the Standard profile."""

import argparse
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from vibesec.sbom import validate_cyclonedx, validate_spdx  # noqa: E402


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--cyclonedx", type=Path, required=True)
    parser.add_argument("--spdx", type=Path, required=True)
    args = parser.parse_args()
    try:
        validate_cyclonedx(args.cyclonedx)
        validate_spdx(args.spdx)
    except ValueError as exc:
        print(exc, file=sys.stderr)
        return 3
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
